const configuredApiBase = document.querySelector('meta[name="api-base"]')?.content || window.PR_PREDICTOR_API_BASE || "http://127.0.0.1:8000";
const API_BASE = configuredApiBase.replace(/\/+$/, "");
const state = { token: localStorage.getItem("pr_admin_token") };
const $ = (id) => document.getElementById(id);
const apiUrl = (path) => `${API_BASE}/admin/api/${path}`;

async function readResponse(response) {
  const text = await response.text();
  let data = {};
  if (text) { try { data = JSON.parse(text); } catch { throw new Error(`Backend returned a non-JSON response (HTTP ${response.status}).`); } }
  if (!response.ok) throw new Error(data.detail || `Request failed (HTTP ${response.status})`);
  return data;
}
function escapeHtml(value) { return String(value ?? "").replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c])); }
function show(authed) { $("login-card").classList.toggle("hidden", authed); $("dashboard").classList.toggle("hidden", !authed); $("logout").classList.toggle("hidden", !authed); }
async function api(path, options = {}) {
  let response;
  try { response = await fetch(apiUrl(path), { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${state.token}`, ...(options.headers || {}) } }); }
  catch { throw new Error(`Cannot connect to the backend at ${API_BASE}.`); }
  return readResponse(response);
}
function renderStats(stats) { $("stats").innerHTML = Object.entries({ Users: stats.users, Predictions: stats.predictions, Models: stats.models, Plans: stats.plans }).map(([name, value]) => `<div class="stat"><span>${name}</span><strong>${value}</strong></div>`).join(""); }
function renderUsers(users) { $("users").innerHTML = users.map(user => `<tr><td>${escapeHtml(user.username)}</td><td>${escapeHtml(user.fullName)}</td><td>${escapeHtml(user.email)}</td><td><select data-id="${escapeHtml(user.userId)}" class="role"><option ${user.role === "USER" ? "selected" : ""}>USER</option><option ${user.role === "ADMIN" ? "selected" : ""}>ADMIN</option></select></td><td><button class="small save-role" data-id="${escapeHtml(user.userId)}" type="button">Save</button></td></tr>`).join(""); document.querySelectorAll(".save-role").forEach(button => button.onclick = async () => { try { const role = document.querySelector(`.role[data-id="${button.dataset.id}"]`).value; await api(`users/${button.dataset.id}/role`, { method: "PATCH", body: JSON.stringify({ role }) }); await load(); } catch (error) { alert(error.message); } }); }
function renderPredictions(items) { $("predictions").innerHTML = items.map(item => `<tr><td>${escapeHtml(item.username || "-")}</td><td>${escapeHtml(item.predictionType)}</td><td>${escapeHtml(item.status)}</td><td>${item.createdAt ? escapeHtml(new Date(item.createdAt).toLocaleString()) : "-"}</td></tr>`).join(""); }
function renderModels(items) { $("models").innerHTML = items.map(model => `<tr><td>${escapeHtml(model.code)}</td><td>${escapeHtml(model.name)}</td><td>${escapeHtml(model.taskType)}</td><td>${escapeHtml(model.version)}</td><td>${escapeHtml(model.creditCost)}</td><td><span class="status ${model.active ? "active" : "inactive"}">${model.active ? "Active" : "Inactive"}</span></td><td><button class="small edit-model" data-id="${escapeHtml(model.modelId)}" type="button">Edit</button> <button class="small ${model.active ? "danger" : "secondary"} toggle-model" data-id="${escapeHtml(model.modelId)}" data-active="${model.active}" type="button">${model.active ? "Delete" : "Activate"}</button></td></tr>`).join(""); document.querySelectorAll(".edit-model").forEach(button => button.onclick = () => openModelForm(items.find(item => item.modelId === button.dataset.id))); document.querySelectorAll(".toggle-model").forEach(button => button.onclick = async () => { const active = button.dataset.active === "true"; try { if (active && !confirm("Deactivate this model?")) return; await api(`models/${button.dataset.id}`, active ? { method: "DELETE" } : { method: "PATCH", body: JSON.stringify({ active: true }) }); await load(); } catch (error) { alert(error.message); } }); }
function renderPlans(items) { $("plans").innerHTML = items.map(plan => `<tr><td>${escapeHtml(plan.code)}</td><td>${escapeHtml(plan.name)}</td><td>${escapeHtml(plan.monthlyCredits)}</td><td>${escapeHtml(plan.parentPlanCode || "-")}</td><td>${escapeHtml((plan.models || []).map(model => model.code).join(", ") || "-")}</td><td><span class="status ${plan.active ? "active" : "inactive"}">${plan.active ? "Active" : "Inactive"}</span></td><td><button class="small edit-plan" data-id="${escapeHtml(plan.planId)}" type="button">Edit</button> <button class="small ${plan.active ? "danger" : "secondary"} toggle-plan" data-id="${escapeHtml(plan.planId)}" data-active="${plan.active}" type="button">${plan.active ? "Delete" : "Activate"}</button></td></tr>`).join(""); document.querySelectorAll(".edit-plan").forEach(button => button.onclick = () => openPlanForm(items.find(item => item.planId === button.dataset.id))); document.querySelectorAll(".toggle-plan").forEach(button => button.onclick = async () => { const active = button.dataset.active === "true"; try { if (active && !confirm("Deactivate this plan?")) return; await api(`plans/${button.dataset.id}`, active ? { method: "DELETE" } : { method: "PATCH", body: JSON.stringify({ active: true }) }); await load(); } catch (error) { alert(error.message); } }); }
async function load() { try { const [stats, users, predictions, models, plans] = await Promise.all([api("stats"), api("users"), api("predictions"), api("models"), api("plans")]); renderStats(stats); renderUsers(users); renderPredictions(predictions); renderModels(models); renderPlans(plans); } catch (error) { if (error.message.toLowerCase().includes("token") || error.message.includes("Admin")) { state.token = null; localStorage.removeItem("pr_admin_token"); show(false); } else alert(error.message); } }
function resetModelForm() { $("model-form").reset(); $("model-id").value = ""; $("model-cost").value = 1; $("model-active").checked = true; $("model-error").textContent = ""; $("model-form").classList.add("hidden"); }
function openModelForm(model = null) { $("model-form").classList.remove("hidden"); $("model-error").textContent = ""; $("model-id").value = model?.modelId || ""; $("model-code").value = model?.code || ""; $("model-name").value = model?.name || ""; $("model-task").value = model?.taskType || "BOTH"; $("model-version").value = model?.version || ""; $("model-provider").value = model?.provider || ""; $("model-cost").value = model?.creditCost || 1; $("model-artifact").value = model?.artifactKey || ""; $("model-description").value = model?.description || ""; $("model-active").checked = model ? model.active : true; $("model-code").focus(); }
function resetPlanForm() { $("plan-form").reset(); $("plan-id").value = ""; $("plan-credits").value = 30; $("plan-active").checked = true; $("plan-error").textContent = ""; $("plan-form").classList.add("hidden"); }
function openPlanForm(plan = null) { $("plan-form").classList.remove("hidden"); $("plan-error").textContent = ""; $("plan-id").value = plan?.planId || ""; $("plan-code").value = plan?.code || ""; $("plan-name").value = plan?.name || ""; $("plan-credits").value = plan?.monthlyCredits ?? 30; $("plan-parent").value = plan?.parentPlanCode || ""; $("plan-models").value = (plan?.directModels || []).map(model => model.code).join(", "); $("plan-description").value = plan?.description || ""; $("plan-active").checked = plan ? plan.active : true; $("plan-code").focus(); }
$("model-form").onsubmit = async (event) => { event.preventDefault(); const id = $("model-id").value; const payload = { code: $("model-code").value, name: $("model-name").value, taskType: $("model-task").value, version: $("model-version").value, provider: $("model-provider").value || null, creditCost: Number($("model-cost").value), artifactKey: $("model-artifact").value || null, description: $("model-description").value || null, active: $("model-active").checked }; try { await api(id ? `models/${id}` : "models", { method: id ? "PATCH" : "POST", body: JSON.stringify(payload) }); resetModelForm(); await load(); } catch (error) { $("model-error").textContent = error.message; } };
$("plan-form").onsubmit = async (event) => { event.preventDefault(); const id = $("plan-id").value; const payload = { code: $("plan-code").value, name: $("plan-name").value, monthlyCredits: Number($("plan-credits").value), parentPlanCode: $("plan-parent").value || null, modelCodes: $("plan-models").value.split(",").map(value => value.trim()).filter(Boolean), description: $("plan-description").value || null, active: $("plan-active").checked }; try { await api(id ? `plans/${id}` : "plans", { method: id ? "PATCH" : "POST", body: JSON.stringify(payload) }); resetPlanForm(); await load(); } catch (error) { $("plan-error").textContent = error.message; } };
$("new-model").onclick = () => openModelForm(); $("cancel-model").onclick = resetModelForm; $("new-plan").onclick = () => openPlanForm(); $("cancel-plan").onclick = resetPlanForm;
$("login-form").onsubmit = async (event) => { event.preventDefault(); $("login-error").textContent = ""; try { const response = await fetch(`${API_BASE}/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: $("username").value, password: $("password").value }) }); const data = await readResponse(response); if (data.user.role !== "ADMIN") throw new Error("This account is not an admin"); state.token = data.accessToken; localStorage.setItem("pr_admin_token", state.token); show(true); await load(); } catch (error) { $("login-error").textContent = error.message; } };
$("logout").onclick = () => { state.token = null; localStorage.removeItem("pr_admin_token"); show(false); }; $("refresh").onclick = load; show(Boolean(state.token)); if (state.token) load();
